// game-center-frontend-angular/src/app/modules/fill-word/components/molecules/components/fill-word-field/fill-word-field.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewEncapsulation
} from "@angular/core";
import {IFillWordAttemptRequest, IFillWordGame, IFillWordGameElement} from "../../../../models/fill-word";

@Component({
  selector: 'app-fill-word-field',
  templateUrl: 'fill-word-field.component.html',
  styleUrls: ['fill-word-field.component.scss'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class FillWordFieldComponent implements OnChanges {
  @Input() model!: IFillWordGame;
  @Output() attempt: EventEmitter<IFillWordAttemptRequest> = new EventEmitter<IFillWordAttemptRequest>();
  private _draw = false;
  private _line: number[] = [];

  ngOnChanges(changes: SimpleChanges) {
    if (changes["model"]) {
      this._line = [];
    }
  }

  // Getters

  public GetSize(): number {
    return Math.sqrt(this.model.matrix.length);
  }

  public get GridClass(): string {
    return "fill-word-field-" + this.GetSize().toString();
  }

  private GetCeilById(id: number): IFillWordGameElement {
    const ceil = this.model.matrix.find((el) => el.id === id);
    if (ceil !== undefined) return ceil;
    throw new Error('No ceil with given id in matrix');
  }

  private GetCeilCoords(id: number): { row: number, ceil: number } {
    const pos = this.model.matrix.map((el) => el.id).indexOf(id);
    return {
      row: Math.trunc(pos / this.GetSize()),
      ceil: pos % this.GetSize()
    }
  }

  private GetPrevCeilId(): number | null {
    return this._line[this._line.length - 2];
  }

  private GetLastCeilId(): number {
    return this._line[this._line.length - 1];
  }

  // DOM actions

  public OnMouseUp(): void {
    if (!this._draw) return;

    this._draw = false;

    if (this._line.length !== 0) {
      this.attempt.emit({
        id: this.model.id,
        answerIds: this._line,
      });
    }
  }

  public OnMouseDown(id: number): void {
    this._draw = true;
    if (this.IsActive(id)) return;
    this.Activate(id);
  }

  public OnMouseOver(id: number): void {
    if (!this._draw) {
      return;
    }

    if (
      !this.IsActive(id) &&
      this.LastCeilLengthEqualOneCeil(id)
    ) {
      this.Activate(id);
    } else {
      if (this.IsPrevCeil(id)) {
        const lastCeilId: number = this.GetLastCeilId();
        this.Disable(lastCeilId);
      }
    }
  }

  // Others

  private IsActive(id: number): boolean {
    return this.GetCeilById(id).active;
  }

  private Activate(id: number): void {
    this.GetCeilById(id).active = true;
    this.AddTimeline(id);
  }

  private Disable(id: number): void {
    this.GetCeilById(id).active = false;
    this.RemoveLastMoveInTimeline();
  }

  private AddTimeline(id: number): void {
    this._line.push(id);
  }

  private RemoveLastMoveInTimeline(): void {
    this._line.splice(this._line.length - 1, 1);
  }

  private IsPrevCeil(id: number): boolean {
    if (!this.GetPrevCeilId()) return false;

    return this.GetPrevCeilId() === id;
  }

  private LastCeilLengthEqualOneCeil(id: number): boolean {
    const lastCeilId: number = this.GetLastCeilId();
    const lastCeilCoords = this.GetCeilCoords(lastCeilId);
    const coords = this.GetCeilCoords(id);

    return (
      ((lastCeilCoords.row === coords.row - 1 ||
          lastCeilCoords.row === coords.row + 1) &&
        lastCeilCoords.ceil === coords.ceil) ||
      ((lastCeilCoords.ceil === coords.ceil - 1 ||
          lastCeilCoords.ceil === coords.ceil + 1) &&
        lastCeilCoords.row === coords.row)
    );
  }
}

<div [class]="GridClass" (mouseleave)="OnMouseUp()">
  <app-fill-word-ceil
    *ngFor="let ceil of model.matrix"
    [active]="ceil.active"
    [letter]="ceil.content"
    (mouseover)="OnMouseOver(ceil.id)"
    (mouseup)="OnMouseUp()"
    (mousedown)="OnMouseDown(ceil.id)"
  ></app-fill-word-ceil>
</div>

// game-center-frontend-vue/src/Presentation/components/molecules/FillWordField.vue
<script lang="ts">
import { Component, Prop, Vue } from "vue-facing-decorator";
import {
  FillWordGameStatus,
  IFillWordGame,
} from "@domain/FillWord/FillWord.models";
import FillWordCeil from "@presentation/components/atoms/FillWordCeil.vue";
import { ID } from "@domain/SharedKernel.types";
import { fillWordModule } from "@presentation/store/modules/fill-word";

export type WordPattern = [number, number];

@Component({
  components: { FillWordCeil },
})
export default class FillWordField extends Vue {
  @Prop({ required: true }) model!: IFillWordGame;
  private draw = false;
  private line: number[] = [];

  public getKey(rowIndex: number, colIndex: number): string {
    return rowIndex.toString() + colIndex.toString();
  }

  public get gridClass(): string {
    return "fill-word-field-" + this.model.matrix.length.toString();
  }

  public onMouseUp(): void {
    if (!this.draw) return;

    this.draw = false;
    const hasWord = fillWordModule.attempt({
      id: this.model.id,
      answerIds: this.line,
    });

    hasWord.then((status) => {
      if (status !== FillWordGameStatus.WRONG_MOVE) {
        this.line = [];
        //
        // if (status === FillWordGameStatus.END_GAME) {
        // }
      } else {
        this.clearTimeLine();
      }
    });
  }

  private onMouseDown(row: number, ceil: number): void {
    this.draw = true;
    if (this.isActive(row, ceil)) return;
    this.activate(row, ceil);
  }

  private onMouseOver(row: number, ceil: number): void {
    if (!this.draw) {
      return;
    }

    if (
      !this.isActive(row, ceil) &&
      this.lastCeilLengthEqualOneCeil(row, ceil)
    ) {
      this.activate(row, ceil);
    } else {
      if (this.isPrevCeil(row, ceil)) {
        const lastCeilId: ID = this.lastCeil();
        const lastCeilCoords = this.findInMatrix(lastCeilId);

        this.disable(lastCeilCoords[0], lastCeilCoords[1]);
        this.removeLastMoveInTimeline();
      }
    }
  }

  private isActive(row: number, ceil: number): boolean {
    return this.model.matrix[row][ceil].active;
  }

  private activate(row: number, ceil: number): void {
    fillWordModule.toggleCeil({ row: row, col: ceil });

    this.addTimeline(row, ceil);
  }

  private disable(row: number, ceil: number) {
    fillWordModule.toggleCeil({ row: row, col: ceil });
  }

  private addTimeline(row: number, ceil: number): void {
    this.line.push(this.model.matrix[row][ceil].id);
  }

  private lastCeilLengthEqualOneCeil(row: number, ceil: number): boolean {
    const lastCeilId: ID = this.lastCeil();
    const lastCeilCoords = this.findInMatrix(lastCeilId);
    const lastRow = lastCeilCoords[0];
    const lastCeil = lastCeilCoords[1];

    return (
      ((lastRow === row - 1 || lastRow === row + 1) && lastCeil === ceil) ||
      ((lastCeil === ceil - 1 || lastCeil === ceil + 1) && lastRow === row)
    );
  }

  private removeLastMoveInTimeline(): void {
    this.line.splice(this.line.length - 1, 1);
  }

  private prevCeil(): ID | null {
    return this.line[this.line.length - 2];
  }

  private lastCeil(): ID {
    return this.line[this.line.length - 1];
  }

  private isPrevCeil(row: number, ceil: number): boolean {
    if (!this.prevCeil()) return false;

    return this.prevCeil() === this.model.matrix[row][ceil].id;
  }

  private clearTimeLine(): void {
    this.line.forEach((id) => {
      this.model.matrix.forEach((row, rowIndex) => {
        const el = row.find((model, colIndex) => {
          if (model.id === id) {
            fillWordModule.toggleCeil({ row: rowIndex, col: colIndex });
          }
        });
      });
    });

    this.line = [];
  }

  private findInMatrix(id: ID): WordPattern {
    let coords: WordPattern | null = null;
    this.model.matrix.forEach((row, rowIndex) =>
      row.forEach((ceil, ceilIndex) => {
        if (ceil.id === id) {
          coords = [rowIndex, ceilIndex];
        }
      })
    );

    if (coords !== null) {
      return coords;
    }

    throw new Error("Not found element with such id");
  }
}
</script>

<template>
  <div :class="gridClass" @mouseleave="onMouseUp">
    <template v-for="(row, rowIndex) in model.matrix">
      <FillWordCeil
        v-for="(col, colIndex) in row"
        :letter="col.content"
        :active="col.active"
        :key="getKey(rowIndex, colIndex)"
        @mouseover="onMouseOver(rowIndex, colIndex)"
        @mousedown="onMouseDown(rowIndex, colIndex)"
        @mouseup="onMouseUp"
      ></FillWordCeil>
    </template>
  </div>
</template>

<style scoped lang="scss">
$grid-size: (3, 4, 5, 6, 7, 8);
@each $value in $grid-size {
  .fill-word-field-#{$value} {
    display: grid;
    gap: 6px;

    width: min-content;
    grid-template-columns: repeat(#{$value}, 1fr);
    grid-auto-rows: repeat(#{$value}, 1fr);
  }
}
</style>
